# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcalculo.proto\x12\x07\x63\x61lculo\"=\n\x0e\x43\x61lculoRequest\x12\n\n\x02op\x18\x01 \x01(\t\x12\t\n\x01\x61\x18\x02 \x01(\x01\x12\t\n\x01\x62\x18\x03 \x01(\x01\x12\t\n\x01n\x18\x04 \x01(\x03\"<\n\x04Part\x12\t\n\x01\x61\x18\x01 \x01(\x03\x12\t\n\x01\x62\x18\x02 \x01(\x03\x12\x0e\n\x06result\x18\x03 \x01(\x03\x12\x0e\n\x06worker\x18\x04 \x01(\t\"\x80\x01\n\x0f\x43\x61lculoResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\x01\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\t\n\x01\x61\x18\x04 \x01(\x03\x12\t\n\x01\x62\x18\x05 \x01(\x03\x12\x0e\n\x06worker\x18\x06 \x01(\t\x12\x1c\n\x05parts\x18\x07 \x03(\x0b\x32\r.calculo.Part2Q\n\x10OperacionService\x12=\n\x08\x43\x61lcular\x12\x17.calculo.CalculoRequest\x1a\x18.calculo.CalculoResponse2S\n\x0e\x43\x61lculoService\x12\x41\n\x0c\x43\x61lculoTotal\x12\x17.calculo.CalculoRequest\x1a\x18.calculo.CalculoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULOREQUEST']._serialized_start=26
  _globals['_CALCULOREQUEST']._serialized_end=87
  _globals['_PART']._serialized_start=89
  _globals['_PART']._serialized_end=149
  _globals['_CALCULORESPONSE']._serialized_start=152
  _globals['_CALCULORESPONSE']._serialized_end=280
  _globals['_OPERACIONSERVICE']._serialized_start=282
  _globals['_OPERACIONSERVICE']._serialized_end=363
  _globals['_CALCULOSERVICE']._serialized_start=365
  _globals['_CALCULOSERVICE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
