# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculo_pb2 as calculo__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperacionServiceStub(object):
    """Servicio que ofrecen los workers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calcular = channel.unary_unary(
                '/calculo.OperacionService/Calcular',
                request_serializer=calculo__pb2.CalculoRequest.SerializeToString,
                response_deserializer=calculo__pb2.CalculoResponse.FromString,
                _registered_method=True)


class OperacionServiceServicer(object):
    """Servicio que ofrecen los workers
    """

    def Calcular(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperacionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calcular': grpc.unary_unary_rpc_method_handler(
                    servicer.Calcular,
                    request_deserializer=calculo__pb2.CalculoRequest.FromString,
                    response_serializer=calculo__pb2.CalculoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculo.OperacionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculo.OperacionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperacionService(object):
    """Servicio que ofrecen los workers
    """

    @staticmethod
    def Calcular(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculo.OperacionService/Calcular',
            calculo__pb2.CalculoRequest.SerializeToString,
            calculo__pb2.CalculoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CalculoServiceStub(object):
    """Servicio que ofrece el servidor de cálculo
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculoTotal = channel.unary_unary(
                '/calculo.CalculoService/CalculoTotal',
                request_serializer=calculo__pb2.CalculoRequest.SerializeToString,
                response_deserializer=calculo__pb2.CalculoResponse.FromString,
                _registered_method=True)


class CalculoServiceServicer(object):
    """Servicio que ofrece el servidor de cálculo
    """

    def CalculoTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculoTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculoTotal,
                    request_deserializer=calculo__pb2.CalculoRequest.FromString,
                    response_serializer=calculo__pb2.CalculoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculo.CalculoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculo.CalculoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalculoService(object):
    """Servicio que ofrece el servidor de cálculo
    """

    @staticmethod
    def CalculoTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculo.CalculoService/CalculoTotal',
            calculo__pb2.CalculoRequest.SerializeToString,
            calculo__pb2.CalculoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
